// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MonitorWall.proto
#ifndef GRPC_MonitorWall_2eproto__INCLUDED
#define GRPC_MonitorWall_2eproto__INCLUDED

#include "MonitorWall.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace MonitorWall {

// *
// ip：192.168.17.63
// port:50051
//
// 定义方法
class SWKJMonitorWall final {
 public:
  static constexpr char const* service_full_name() {
    return "MonitorWall.SWKJMonitorWall";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::MonitorWall::empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>> Asynclogin(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>>(AsyncloginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>> PrepareAsynclogin(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>>(PrepareAsyncloginRaw(context, request, cq));
    }
    virtual ::grpc::Status getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::MonitorWall::decoderOutTVNumResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::decoderOutTVNumResponse>> AsyncgetTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::decoderOutTVNumResponse>>(AsyncgetTVNumRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::decoderOutTVNumResponse>> PrepareAsyncgetTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::decoderOutTVNumResponse>>(PrepareAsyncgetTVNumRaw(context, request, cq));
    }
    virtual ::grpc::Status createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::MonitorWall::empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>> AsynccreateWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>>(AsynccreateWallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>> PrepareAsynccreateWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>>(PrepareAsynccreateWallRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>* AsyncloginRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>* PrepareAsyncloginRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::decoderOutTVNumResponse>* AsyncgetTVNumRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::decoderOutTVNumResponse>* PrepareAsyncgetTVNumRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>* AsynccreateWallRaw(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MonitorWall::empty>* PrepareAsynccreateWallRaw(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::MonitorWall::empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>> Asynclogin(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>>(AsyncloginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>> PrepareAsynclogin(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>>(PrepareAsyncloginRaw(context, request, cq));
    }
    ::grpc::Status getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::MonitorWall::decoderOutTVNumResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>> AsyncgetTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>>(AsyncgetTVNumRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>> PrepareAsyncgetTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>>(PrepareAsyncgetTVNumRaw(context, request, cq));
    }
    ::grpc::Status createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::MonitorWall::empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>> AsynccreateWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>>(AsynccreateWallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>> PrepareAsynccreateWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>>(PrepareAsynccreateWallRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) override;
      void login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, std::function<void(::grpc::Status)>) override;
      void getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) override;
      void createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* AsyncloginRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* PrepareAsyncloginRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>* AsyncgetTVNumRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>* PrepareAsyncgetTVNumRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* AsynccreateWallRaw(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* PrepareAsynccreateWallRaw(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_login_;
    const ::grpc::internal::RpcMethod rpcmethod_getTVNum_;
    const ::grpc::internal::RpcMethod rpcmethod_createWall_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status login(::grpc::ServerContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response);
    virtual ::grpc::Status getTVNum(::grpc::ServerContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response);
    virtual ::grpc::Status createWall(::grpc::ServerContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_login() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status login(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestlogin(::grpc::ServerContext* context, ::MonitorWall::loginRequest* request, ::grpc::ServerAsyncResponseWriter< ::MonitorWall::empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getTVNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getTVNum() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getTVNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getTVNum(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetTVNum(::grpc::ServerContext* context, ::MonitorWall::loginRequest* request, ::grpc::ServerAsyncResponseWriter< ::MonitorWall::decoderOutTVNumResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_createWall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_createWall() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_createWall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createWall(::grpc::ServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcreateWall(::grpc::ServerContext* context, ::MonitorWall::wallConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::MonitorWall::empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_login<WithAsyncMethod_getTVNum<WithAsyncMethod_createWall<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_login() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::MonitorWall::loginRequest, ::MonitorWall::empty>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response) { return this->login(context, request, response); }));}
    void SetMessageAllocatorFor_login(
        ::grpc::experimental::MessageAllocator< ::MonitorWall::loginRequest, ::MonitorWall::empty>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::MonitorWall::loginRequest, ::MonitorWall::empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status login(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* login(
      ::grpc::CallbackServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* login(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getTVNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getTVNum() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::MonitorWall::loginRequest, ::MonitorWall::decoderOutTVNumResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response) { return this->getTVNum(context, request, response); }));}
    void SetMessageAllocatorFor_getTVNum(
        ::grpc::experimental::MessageAllocator< ::MonitorWall::loginRequest, ::MonitorWall::decoderOutTVNumResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::MonitorWall::loginRequest, ::MonitorWall::decoderOutTVNumResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getTVNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getTVNum(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getTVNum(
      ::grpc::CallbackServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getTVNum(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_createWall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_createWall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::MonitorWall::wallConfigRequest, ::MonitorWall::empty>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response) { return this->createWall(context, request, response); }));}
    void SetMessageAllocatorFor_createWall(
        ::grpc::experimental::MessageAllocator< ::MonitorWall::wallConfigRequest, ::MonitorWall::empty>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::MonitorWall::wallConfigRequest, ::MonitorWall::empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_createWall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createWall(::grpc::ServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* createWall(
      ::grpc::CallbackServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* createWall(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_login<ExperimentalWithCallbackMethod_getTVNum<ExperimentalWithCallbackMethod_createWall<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_login<ExperimentalWithCallbackMethod_getTVNum<ExperimentalWithCallbackMethod_createWall<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_login() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status login(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getTVNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getTVNum() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getTVNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getTVNum(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_createWall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_createWall() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_createWall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createWall(::grpc::ServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_login() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status login(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestlogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getTVNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getTVNum() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getTVNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getTVNum(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetTVNum(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_createWall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_createWall() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_createWall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createWall(::grpc::ServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcreateWall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_login() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->login(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status login(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* login(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* login(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getTVNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getTVNum() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getTVNum(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getTVNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getTVNum(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getTVNum(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getTVNum(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_createWall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_createWall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->createWall(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_createWall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status createWall(::grpc::ServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* createWall(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* createWall(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_login() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::MonitorWall::loginRequest, ::MonitorWall::empty>(std::bind(&WithStreamedUnaryMethod_login<BaseClass>::Streamedlogin, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status login(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedlogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MonitorWall::loginRequest,::MonitorWall::empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getTVNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getTVNum() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::MonitorWall::loginRequest, ::MonitorWall::decoderOutTVNumResponse>(std::bind(&WithStreamedUnaryMethod_getTVNum<BaseClass>::StreamedgetTVNum, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_getTVNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getTVNum(::grpc::ServerContext* /*context*/, const ::MonitorWall::loginRequest* /*request*/, ::MonitorWall::decoderOutTVNumResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetTVNum(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MonitorWall::loginRequest,::MonitorWall::decoderOutTVNumResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_createWall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_createWall() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::MonitorWall::wallConfigRequest, ::MonitorWall::empty>(std::bind(&WithStreamedUnaryMethod_createWall<BaseClass>::StreamedcreateWall, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_createWall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status createWall(::grpc::ServerContext* /*context*/, const ::MonitorWall::wallConfigRequest* /*request*/, ::MonitorWall::empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcreateWall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MonitorWall::wallConfigRequest,::MonitorWall::empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_login<WithStreamedUnaryMethod_getTVNum<WithStreamedUnaryMethod_createWall<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_login<WithStreamedUnaryMethod_getTVNum<WithStreamedUnaryMethod_createWall<Service > > > StreamedService;
};

}  // namespace MonitorWall


#endif  // GRPC_MonitorWall_2eproto__INCLUDED
