// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorWall.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MonitorWall_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MonitorWall_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MonitorWall_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MonitorWall_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MonitorWall_2eproto;
namespace MonitorWall {
class blockMes;
class blockMesDefaultTypeInternal;
extern blockMesDefaultTypeInternal _blockMes_default_instance_;
class decoderOutTVNumResponse;
class decoderOutTVNumResponseDefaultTypeInternal;
extern decoderOutTVNumResponseDefaultTypeInternal _decoderOutTVNumResponse_default_instance_;
class empty;
class emptyDefaultTypeInternal;
extern emptyDefaultTypeInternal _empty_default_instance_;
class loginRequest;
class loginRequestDefaultTypeInternal;
extern loginRequestDefaultTypeInternal _loginRequest_default_instance_;
class wallConfigRequest;
class wallConfigRequestDefaultTypeInternal;
extern wallConfigRequestDefaultTypeInternal _wallConfigRequest_default_instance_;
}  // namespace MonitorWall
PROTOBUF_NAMESPACE_OPEN
template<> ::MonitorWall::blockMes* Arena::CreateMaybeMessage<::MonitorWall::blockMes>(Arena*);
template<> ::MonitorWall::decoderOutTVNumResponse* Arena::CreateMaybeMessage<::MonitorWall::decoderOutTVNumResponse>(Arena*);
template<> ::MonitorWall::empty* Arena::CreateMaybeMessage<::MonitorWall::empty>(Arena*);
template<> ::MonitorWall::loginRequest* Arena::CreateMaybeMessage<::MonitorWall::loginRequest>(Arena*);
template<> ::MonitorWall::wallConfigRequest* Arena::CreateMaybeMessage<::MonitorWall::wallConfigRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace MonitorWall {

// ===================================================================

class empty :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MonitorWall.empty) */ {
 public:
  empty();
  virtual ~empty();

  empty(const empty& from);
  empty(empty&& from) noexcept
    : empty() {
    *this = ::std::move(from);
  }

  inline empty& operator=(const empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline empty& operator=(empty&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const empty& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const empty* internal_default_instance() {
    return reinterpret_cast<const empty*>(
               &_empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(empty& a, empty& b) {
    a.Swap(&b);
  }
  inline void Swap(empty* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline empty* New() const final {
    return CreateMaybeMessage<empty>(nullptr);
  }

  empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<empty>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const empty& from);
  void MergeFrom(const empty& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(empty* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MonitorWall.empty";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MonitorWall_2eproto);
    return ::descriptor_table_MonitorWall_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:MonitorWall.empty)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MonitorWall_2eproto;
};
// -------------------------------------------------------------------

class loginRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MonitorWall.loginRequest) */ {
 public:
  loginRequest();
  virtual ~loginRequest();

  loginRequest(const loginRequest& from);
  loginRequest(loginRequest&& from) noexcept
    : loginRequest() {
    *this = ::std::move(from);
  }

  inline loginRequest& operator=(const loginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline loginRequest& operator=(loginRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const loginRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const loginRequest* internal_default_instance() {
    return reinterpret_cast<const loginRequest*>(
               &_loginRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(loginRequest& a, loginRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(loginRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline loginRequest* New() const final {
    return CreateMaybeMessage<loginRequest>(nullptr);
  }

  loginRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<loginRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const loginRequest& from);
  void MergeFrom(const loginRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(loginRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MonitorWall.loginRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MonitorWall_2eproto);
    return ::descriptor_table_MonitorWall_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDecoderIpFieldNumber = 1,
    kDecoderUsernameFieldNumber = 3,
    kDecoderPwdFieldNumber = 4,
    kDecoderPortFieldNumber = 2,
  };
  // string decoder_ip = 1;
  void clear_decoder_ip();
  const std::string& decoder_ip() const;
  void set_decoder_ip(const std::string& value);
  void set_decoder_ip(std::string&& value);
  void set_decoder_ip(const char* value);
  void set_decoder_ip(const char* value, size_t size);
  std::string* mutable_decoder_ip();
  std::string* release_decoder_ip();
  void set_allocated_decoder_ip(std::string* decoder_ip);
  private:
  const std::string& _internal_decoder_ip() const;
  void _internal_set_decoder_ip(const std::string& value);
  std::string* _internal_mutable_decoder_ip();
  public:

  // string decoder_username = 3;
  void clear_decoder_username();
  const std::string& decoder_username() const;
  void set_decoder_username(const std::string& value);
  void set_decoder_username(std::string&& value);
  void set_decoder_username(const char* value);
  void set_decoder_username(const char* value, size_t size);
  std::string* mutable_decoder_username();
  std::string* release_decoder_username();
  void set_allocated_decoder_username(std::string* decoder_username);
  private:
  const std::string& _internal_decoder_username() const;
  void _internal_set_decoder_username(const std::string& value);
  std::string* _internal_mutable_decoder_username();
  public:

  // string decoder_pwd = 4;
  void clear_decoder_pwd();
  const std::string& decoder_pwd() const;
  void set_decoder_pwd(const std::string& value);
  void set_decoder_pwd(std::string&& value);
  void set_decoder_pwd(const char* value);
  void set_decoder_pwd(const char* value, size_t size);
  std::string* mutable_decoder_pwd();
  std::string* release_decoder_pwd();
  void set_allocated_decoder_pwd(std::string* decoder_pwd);
  private:
  const std::string& _internal_decoder_pwd() const;
  void _internal_set_decoder_pwd(const std::string& value);
  std::string* _internal_mutable_decoder_pwd();
  public:

  // uint32 decoder_port = 2;
  void clear_decoder_port();
  ::PROTOBUF_NAMESPACE_ID::uint32 decoder_port() const;
  void set_decoder_port(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_decoder_port() const;
  void _internal_set_decoder_port(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:MonitorWall.loginRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr decoder_ip_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr decoder_username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr decoder_pwd_;
  ::PROTOBUF_NAMESPACE_ID::uint32 decoder_port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MonitorWall_2eproto;
};
// -------------------------------------------------------------------

class decoderOutTVNumResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MonitorWall.decoderOutTVNumResponse) */ {
 public:
  decoderOutTVNumResponse();
  virtual ~decoderOutTVNumResponse();

  decoderOutTVNumResponse(const decoderOutTVNumResponse& from);
  decoderOutTVNumResponse(decoderOutTVNumResponse&& from) noexcept
    : decoderOutTVNumResponse() {
    *this = ::std::move(from);
  }

  inline decoderOutTVNumResponse& operator=(const decoderOutTVNumResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline decoderOutTVNumResponse& operator=(decoderOutTVNumResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const decoderOutTVNumResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const decoderOutTVNumResponse* internal_default_instance() {
    return reinterpret_cast<const decoderOutTVNumResponse*>(
               &_decoderOutTVNumResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(decoderOutTVNumResponse& a, decoderOutTVNumResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(decoderOutTVNumResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline decoderOutTVNumResponse* New() const final {
    return CreateMaybeMessage<decoderOutTVNumResponse>(nullptr);
  }

  decoderOutTVNumResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<decoderOutTVNumResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const decoderOutTVNumResponse& from);
  void MergeFrom(const decoderOutTVNumResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(decoderOutTVNumResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MonitorWall.decoderOutTVNumResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MonitorWall_2eproto);
    return ::descriptor_table_MonitorWall_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTvNumFieldNumber = 1,
  };
  // int32 tv_num = 1;
  void clear_tv_num();
  ::PROTOBUF_NAMESPACE_ID::int32 tv_num() const;
  void set_tv_num(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_tv_num() const;
  void _internal_set_tv_num(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MonitorWall.decoderOutTVNumResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 tv_num_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MonitorWall_2eproto;
};
// -------------------------------------------------------------------

class blockMes :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MonitorWall.blockMes) */ {
 public:
  blockMes();
  virtual ~blockMes();

  blockMes(const blockMes& from);
  blockMes(blockMes&& from) noexcept
    : blockMes() {
    *this = ::std::move(from);
  }

  inline blockMes& operator=(const blockMes& from) {
    CopyFrom(from);
    return *this;
  }
  inline blockMes& operator=(blockMes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const blockMes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const blockMes* internal_default_instance() {
    return reinterpret_cast<const blockMes*>(
               &_blockMes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(blockMes& a, blockMes& b) {
    a.Swap(&b);
  }
  inline void Swap(blockMes* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline blockMes* New() const final {
    return CreateMaybeMessage<blockMes>(nullptr);
  }

  blockMes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<blockMes>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const blockMes& from);
  void MergeFrom(const blockMes& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(blockMes* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MonitorWall.blockMes";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MonitorWall_2eproto);
    return ::descriptor_table_MonitorWall_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBindLineFieldNumber = 1,
    kBindColFieldNumber = 2,
    kBindChFieldNumber = 3,
  };
  // int32 bind_line = 1;
  void clear_bind_line();
  ::PROTOBUF_NAMESPACE_ID::int32 bind_line() const;
  void set_bind_line(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_bind_line() const;
  void _internal_set_bind_line(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 bind_col = 2;
  void clear_bind_col();
  ::PROTOBUF_NAMESPACE_ID::int32 bind_col() const;
  void set_bind_col(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_bind_col() const;
  void _internal_set_bind_col(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 bind_ch = 3;
  void clear_bind_ch();
  ::PROTOBUF_NAMESPACE_ID::int32 bind_ch() const;
  void set_bind_ch(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_bind_ch() const;
  void _internal_set_bind_ch(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MonitorWall.blockMes)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 bind_line_;
  ::PROTOBUF_NAMESPACE_ID::int32 bind_col_;
  ::PROTOBUF_NAMESPACE_ID::int32 bind_ch_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MonitorWall_2eproto;
};
// -------------------------------------------------------------------

class wallConfigRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MonitorWall.wallConfigRequest) */ {
 public:
  wallConfigRequest();
  virtual ~wallConfigRequest();

  wallConfigRequest(const wallConfigRequest& from);
  wallConfigRequest(wallConfigRequest&& from) noexcept
    : wallConfigRequest() {
    *this = ::std::move(from);
  }

  inline wallConfigRequest& operator=(const wallConfigRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline wallConfigRequest& operator=(wallConfigRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const wallConfigRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const wallConfigRequest* internal_default_instance() {
    return reinterpret_cast<const wallConfigRequest*>(
               &_wallConfigRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(wallConfigRequest& a, wallConfigRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(wallConfigRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline wallConfigRequest* New() const final {
    return CreateMaybeMessage<wallConfigRequest>(nullptr);
  }

  wallConfigRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<wallConfigRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const wallConfigRequest& from);
  void MergeFrom(const wallConfigRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(wallConfigRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MonitorWall.wallConfigRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MonitorWall_2eproto);
    return ::descriptor_table_MonitorWall_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockFieldNumber = 3,
    kLineFieldNumber = 1,
    kColunmFieldNumber = 2,
  };
  // repeated .MonitorWall.blockMes block = 3;
  int block_size() const;
  private:
  int _internal_block_size() const;
  public:
  void clear_block();
  ::MonitorWall::blockMes* mutable_block(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MonitorWall::blockMes >*
      mutable_block();
  private:
  const ::MonitorWall::blockMes& _internal_block(int index) const;
  ::MonitorWall::blockMes* _internal_add_block();
  public:
  const ::MonitorWall::blockMes& block(int index) const;
  ::MonitorWall::blockMes* add_block();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MonitorWall::blockMes >&
      block() const;

  // int32 line = 1;
  void clear_line();
  ::PROTOBUF_NAMESPACE_ID::int32 line() const;
  void set_line(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_line() const;
  void _internal_set_line(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 colunm = 2;
  void clear_colunm();
  ::PROTOBUF_NAMESPACE_ID::int32 colunm() const;
  void set_colunm(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_colunm() const;
  void _internal_set_colunm(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MonitorWall.wallConfigRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MonitorWall::blockMes > block_;
  ::PROTOBUF_NAMESPACE_ID::int32 line_;
  ::PROTOBUF_NAMESPACE_ID::int32 colunm_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MonitorWall_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// empty

// -------------------------------------------------------------------

// loginRequest

// string decoder_ip = 1;
inline void loginRequest::clear_decoder_ip() {
  decoder_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& loginRequest::decoder_ip() const {
  // @@protoc_insertion_point(field_get:MonitorWall.loginRequest.decoder_ip)
  return _internal_decoder_ip();
}
inline void loginRequest::set_decoder_ip(const std::string& value) {
  _internal_set_decoder_ip(value);
  // @@protoc_insertion_point(field_set:MonitorWall.loginRequest.decoder_ip)
}
inline std::string* loginRequest::mutable_decoder_ip() {
  // @@protoc_insertion_point(field_mutable:MonitorWall.loginRequest.decoder_ip)
  return _internal_mutable_decoder_ip();
}
inline const std::string& loginRequest::_internal_decoder_ip() const {
  return decoder_ip_.GetNoArena();
}
inline void loginRequest::_internal_set_decoder_ip(const std::string& value) {
  
  decoder_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void loginRequest::set_decoder_ip(std::string&& value) {
  
  decoder_ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MonitorWall.loginRequest.decoder_ip)
}
inline void loginRequest::set_decoder_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  decoder_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MonitorWall.loginRequest.decoder_ip)
}
inline void loginRequest::set_decoder_ip(const char* value, size_t size) {
  
  decoder_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MonitorWall.loginRequest.decoder_ip)
}
inline std::string* loginRequest::_internal_mutable_decoder_ip() {
  
  return decoder_ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* loginRequest::release_decoder_ip() {
  // @@protoc_insertion_point(field_release:MonitorWall.loginRequest.decoder_ip)
  
  return decoder_ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void loginRequest::set_allocated_decoder_ip(std::string* decoder_ip) {
  if (decoder_ip != nullptr) {
    
  } else {
    
  }
  decoder_ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), decoder_ip);
  // @@protoc_insertion_point(field_set_allocated:MonitorWall.loginRequest.decoder_ip)
}

// uint32 decoder_port = 2;
inline void loginRequest::clear_decoder_port() {
  decoder_port_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 loginRequest::_internal_decoder_port() const {
  return decoder_port_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 loginRequest::decoder_port() const {
  // @@protoc_insertion_point(field_get:MonitorWall.loginRequest.decoder_port)
  return _internal_decoder_port();
}
inline void loginRequest::_internal_set_decoder_port(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  decoder_port_ = value;
}
inline void loginRequest::set_decoder_port(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_decoder_port(value);
  // @@protoc_insertion_point(field_set:MonitorWall.loginRequest.decoder_port)
}

// string decoder_username = 3;
inline void loginRequest::clear_decoder_username() {
  decoder_username_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& loginRequest::decoder_username() const {
  // @@protoc_insertion_point(field_get:MonitorWall.loginRequest.decoder_username)
  return _internal_decoder_username();
}
inline void loginRequest::set_decoder_username(const std::string& value) {
  _internal_set_decoder_username(value);
  // @@protoc_insertion_point(field_set:MonitorWall.loginRequest.decoder_username)
}
inline std::string* loginRequest::mutable_decoder_username() {
  // @@protoc_insertion_point(field_mutable:MonitorWall.loginRequest.decoder_username)
  return _internal_mutable_decoder_username();
}
inline const std::string& loginRequest::_internal_decoder_username() const {
  return decoder_username_.GetNoArena();
}
inline void loginRequest::_internal_set_decoder_username(const std::string& value) {
  
  decoder_username_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void loginRequest::set_decoder_username(std::string&& value) {
  
  decoder_username_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MonitorWall.loginRequest.decoder_username)
}
inline void loginRequest::set_decoder_username(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  decoder_username_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MonitorWall.loginRequest.decoder_username)
}
inline void loginRequest::set_decoder_username(const char* value, size_t size) {
  
  decoder_username_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MonitorWall.loginRequest.decoder_username)
}
inline std::string* loginRequest::_internal_mutable_decoder_username() {
  
  return decoder_username_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* loginRequest::release_decoder_username() {
  // @@protoc_insertion_point(field_release:MonitorWall.loginRequest.decoder_username)
  
  return decoder_username_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void loginRequest::set_allocated_decoder_username(std::string* decoder_username) {
  if (decoder_username != nullptr) {
    
  } else {
    
  }
  decoder_username_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), decoder_username);
  // @@protoc_insertion_point(field_set_allocated:MonitorWall.loginRequest.decoder_username)
}

// string decoder_pwd = 4;
inline void loginRequest::clear_decoder_pwd() {
  decoder_pwd_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& loginRequest::decoder_pwd() const {
  // @@protoc_insertion_point(field_get:MonitorWall.loginRequest.decoder_pwd)
  return _internal_decoder_pwd();
}
inline void loginRequest::set_decoder_pwd(const std::string& value) {
  _internal_set_decoder_pwd(value);
  // @@protoc_insertion_point(field_set:MonitorWall.loginRequest.decoder_pwd)
}
inline std::string* loginRequest::mutable_decoder_pwd() {
  // @@protoc_insertion_point(field_mutable:MonitorWall.loginRequest.decoder_pwd)
  return _internal_mutable_decoder_pwd();
}
inline const std::string& loginRequest::_internal_decoder_pwd() const {
  return decoder_pwd_.GetNoArena();
}
inline void loginRequest::_internal_set_decoder_pwd(const std::string& value) {
  
  decoder_pwd_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void loginRequest::set_decoder_pwd(std::string&& value) {
  
  decoder_pwd_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MonitorWall.loginRequest.decoder_pwd)
}
inline void loginRequest::set_decoder_pwd(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  decoder_pwd_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MonitorWall.loginRequest.decoder_pwd)
}
inline void loginRequest::set_decoder_pwd(const char* value, size_t size) {
  
  decoder_pwd_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MonitorWall.loginRequest.decoder_pwd)
}
inline std::string* loginRequest::_internal_mutable_decoder_pwd() {
  
  return decoder_pwd_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* loginRequest::release_decoder_pwd() {
  // @@protoc_insertion_point(field_release:MonitorWall.loginRequest.decoder_pwd)
  
  return decoder_pwd_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void loginRequest::set_allocated_decoder_pwd(std::string* decoder_pwd) {
  if (decoder_pwd != nullptr) {
    
  } else {
    
  }
  decoder_pwd_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), decoder_pwd);
  // @@protoc_insertion_point(field_set_allocated:MonitorWall.loginRequest.decoder_pwd)
}

// -------------------------------------------------------------------

// decoderOutTVNumResponse

// int32 tv_num = 1;
inline void decoderOutTVNumResponse::clear_tv_num() {
  tv_num_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 decoderOutTVNumResponse::_internal_tv_num() const {
  return tv_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 decoderOutTVNumResponse::tv_num() const {
  // @@protoc_insertion_point(field_get:MonitorWall.decoderOutTVNumResponse.tv_num)
  return _internal_tv_num();
}
inline void decoderOutTVNumResponse::_internal_set_tv_num(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  tv_num_ = value;
}
inline void decoderOutTVNumResponse::set_tv_num(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_tv_num(value);
  // @@protoc_insertion_point(field_set:MonitorWall.decoderOutTVNumResponse.tv_num)
}

// -------------------------------------------------------------------

// blockMes

// int32 bind_line = 1;
inline void blockMes::clear_bind_line() {
  bind_line_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 blockMes::_internal_bind_line() const {
  return bind_line_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 blockMes::bind_line() const {
  // @@protoc_insertion_point(field_get:MonitorWall.blockMes.bind_line)
  return _internal_bind_line();
}
inline void blockMes::_internal_set_bind_line(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  bind_line_ = value;
}
inline void blockMes::set_bind_line(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_bind_line(value);
  // @@protoc_insertion_point(field_set:MonitorWall.blockMes.bind_line)
}

// int32 bind_col = 2;
inline void blockMes::clear_bind_col() {
  bind_col_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 blockMes::_internal_bind_col() const {
  return bind_col_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 blockMes::bind_col() const {
  // @@protoc_insertion_point(field_get:MonitorWall.blockMes.bind_col)
  return _internal_bind_col();
}
inline void blockMes::_internal_set_bind_col(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  bind_col_ = value;
}
inline void blockMes::set_bind_col(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_bind_col(value);
  // @@protoc_insertion_point(field_set:MonitorWall.blockMes.bind_col)
}

// int32 bind_ch = 3;
inline void blockMes::clear_bind_ch() {
  bind_ch_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 blockMes::_internal_bind_ch() const {
  return bind_ch_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 blockMes::bind_ch() const {
  // @@protoc_insertion_point(field_get:MonitorWall.blockMes.bind_ch)
  return _internal_bind_ch();
}
inline void blockMes::_internal_set_bind_ch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  bind_ch_ = value;
}
inline void blockMes::set_bind_ch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_bind_ch(value);
  // @@protoc_insertion_point(field_set:MonitorWall.blockMes.bind_ch)
}

// -------------------------------------------------------------------

// wallConfigRequest

// int32 line = 1;
inline void wallConfigRequest::clear_line() {
  line_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 wallConfigRequest::_internal_line() const {
  return line_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 wallConfigRequest::line() const {
  // @@protoc_insertion_point(field_get:MonitorWall.wallConfigRequest.line)
  return _internal_line();
}
inline void wallConfigRequest::_internal_set_line(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  line_ = value;
}
inline void wallConfigRequest::set_line(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_line(value);
  // @@protoc_insertion_point(field_set:MonitorWall.wallConfigRequest.line)
}

// int32 colunm = 2;
inline void wallConfigRequest::clear_colunm() {
  colunm_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 wallConfigRequest::_internal_colunm() const {
  return colunm_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 wallConfigRequest::colunm() const {
  // @@protoc_insertion_point(field_get:MonitorWall.wallConfigRequest.colunm)
  return _internal_colunm();
}
inline void wallConfigRequest::_internal_set_colunm(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  colunm_ = value;
}
inline void wallConfigRequest::set_colunm(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_colunm(value);
  // @@protoc_insertion_point(field_set:MonitorWall.wallConfigRequest.colunm)
}

// repeated .MonitorWall.blockMes block = 3;
inline int wallConfigRequest::_internal_block_size() const {
  return block_.size();
}
inline int wallConfigRequest::block_size() const {
  return _internal_block_size();
}
inline void wallConfigRequest::clear_block() {
  block_.Clear();
}
inline ::MonitorWall::blockMes* wallConfigRequest::mutable_block(int index) {
  // @@protoc_insertion_point(field_mutable:MonitorWall.wallConfigRequest.block)
  return block_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MonitorWall::blockMes >*
wallConfigRequest::mutable_block() {
  // @@protoc_insertion_point(field_mutable_list:MonitorWall.wallConfigRequest.block)
  return &block_;
}
inline const ::MonitorWall::blockMes& wallConfigRequest::_internal_block(int index) const {
  return block_.Get(index);
}
inline const ::MonitorWall::blockMes& wallConfigRequest::block(int index) const {
  // @@protoc_insertion_point(field_get:MonitorWall.wallConfigRequest.block)
  return _internal_block(index);
}
inline ::MonitorWall::blockMes* wallConfigRequest::_internal_add_block() {
  return block_.Add();
}
inline ::MonitorWall::blockMes* wallConfigRequest::add_block() {
  // @@protoc_insertion_point(field_add:MonitorWall.wallConfigRequest.block)
  return _internal_add_block();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MonitorWall::blockMes >&
wallConfigRequest::block() const {
  // @@protoc_insertion_point(field_list:MonitorWall.wallConfigRequest.block)
  return block_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MonitorWall

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MonitorWall_2eproto
