// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MonitorWall.proto

#include "MonitorWall.pb.h"
#include "MonitorWall.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace MonitorWall {

static const char* SWKJMonitorWall_method_names[] = {
  "/MonitorWall.SWKJMonitorWall/login",
  "/MonitorWall.SWKJMonitorWall/getTVNum",
  "/MonitorWall.SWKJMonitorWall/createWall",
};

std::unique_ptr< SWKJMonitorWall::Stub> SWKJMonitorWall::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SWKJMonitorWall::Stub> stub(new SWKJMonitorWall::Stub(channel));
  return stub;
}

SWKJMonitorWall::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_login_(SWKJMonitorWall_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getTVNum_(SWKJMonitorWall_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_createWall_(SWKJMonitorWall_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SWKJMonitorWall::Stub::login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::MonitorWall::empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_login_, context, request, response);
}

void SWKJMonitorWall::Stub::experimental_async::login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_login_, context, request, response, std::move(f));
}

void SWKJMonitorWall::Stub::experimental_async::login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_login_, context, request, response, std::move(f));
}

void SWKJMonitorWall::Stub::experimental_async::login(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_login_, context, request, response, reactor);
}

void SWKJMonitorWall::Stub::experimental_async::login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* SWKJMonitorWall::Stub::AsyncloginRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MonitorWall::empty>::Create(channel_.get(), cq, rpcmethod_login_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* SWKJMonitorWall::Stub::PrepareAsyncloginRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MonitorWall::empty>::Create(channel_.get(), cq, rpcmethod_login_, context, request, false);
}

::grpc::Status SWKJMonitorWall::Stub::getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::MonitorWall::decoderOutTVNumResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_getTVNum_, context, request, response);
}

void SWKJMonitorWall::Stub::experimental_async::getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_getTVNum_, context, request, response, std::move(f));
}

void SWKJMonitorWall::Stub::experimental_async::getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_getTVNum_, context, request, response, std::move(f));
}

void SWKJMonitorWall::Stub::experimental_async::getTVNum(::grpc::ClientContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_getTVNum_, context, request, response, reactor);
}

void SWKJMonitorWall::Stub::experimental_async::getTVNum(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::decoderOutTVNumResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_getTVNum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>* SWKJMonitorWall::Stub::AsyncgetTVNumRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MonitorWall::decoderOutTVNumResponse>::Create(channel_.get(), cq, rpcmethod_getTVNum_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::MonitorWall::decoderOutTVNumResponse>* SWKJMonitorWall::Stub::PrepareAsyncgetTVNumRaw(::grpc::ClientContext* context, const ::MonitorWall::loginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MonitorWall::decoderOutTVNumResponse>::Create(channel_.get(), cq, rpcmethod_getTVNum_, context, request, false);
}

::grpc::Status SWKJMonitorWall::Stub::createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::MonitorWall::empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_createWall_, context, request, response);
}

void SWKJMonitorWall::Stub::experimental_async::createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_createWall_, context, request, response, std::move(f));
}

void SWKJMonitorWall::Stub::experimental_async::createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_createWall_, context, request, response, std::move(f));
}

void SWKJMonitorWall::Stub::experimental_async::createWall(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_createWall_, context, request, response, reactor);
}

void SWKJMonitorWall::Stub::experimental_async::createWall(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MonitorWall::empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_createWall_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* SWKJMonitorWall::Stub::AsynccreateWallRaw(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MonitorWall::empty>::Create(channel_.get(), cq, rpcmethod_createWall_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::MonitorWall::empty>* SWKJMonitorWall::Stub::PrepareAsynccreateWallRaw(::grpc::ClientContext* context, const ::MonitorWall::wallConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MonitorWall::empty>::Create(channel_.get(), cq, rpcmethod_createWall_, context, request, false);
}

SWKJMonitorWall::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SWKJMonitorWall_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SWKJMonitorWall::Service, ::MonitorWall::loginRequest, ::MonitorWall::empty>(
          std::mem_fn(&SWKJMonitorWall::Service::login), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SWKJMonitorWall_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SWKJMonitorWall::Service, ::MonitorWall::loginRequest, ::MonitorWall::decoderOutTVNumResponse>(
          std::mem_fn(&SWKJMonitorWall::Service::getTVNum), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SWKJMonitorWall_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SWKJMonitorWall::Service, ::MonitorWall::wallConfigRequest, ::MonitorWall::empty>(
          std::mem_fn(&SWKJMonitorWall::Service::createWall), this)));
}

SWKJMonitorWall::Service::~Service() {
}

::grpc::Status SWKJMonitorWall::Service::login(::grpc::ServerContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SWKJMonitorWall::Service::getTVNum(::grpc::ServerContext* context, const ::MonitorWall::loginRequest* request, ::MonitorWall::decoderOutTVNumResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SWKJMonitorWall::Service::createWall(::grpc::ServerContext* context, const ::MonitorWall::wallConfigRequest* request, ::MonitorWall::empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace MonitorWall

