// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorWall.proto

#include "MonitorWall.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_MonitorWall_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_blockMes_MonitorWall_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_MonitorWall_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_loginRequest_MonitorWall_2eproto;
namespace MonitorWall {
class emptyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<empty> _instance;
} _empty_default_instance_;
class loginRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<loginRequest> _instance;
} _loginRequest_default_instance_;
class decoderOutTVNumResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<decoderOutTVNumResponse> _instance;
} _decoderOutTVNumResponse_default_instance_;
class blockMesDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<blockMes> _instance;
} _blockMes_default_instance_;
class wallConfigRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<wallConfigRequest> _instance;
} _wallConfigRequest_default_instance_;
}  // namespace MonitorWall
static void InitDefaultsscc_info_blockMes_MonitorWall_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MonitorWall::_blockMes_default_instance_;
    new (ptr) ::MonitorWall::blockMes();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MonitorWall::blockMes::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_blockMes_MonitorWall_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_blockMes_MonitorWall_2eproto}, {}};

static void InitDefaultsscc_info_decoderOutTVNumResponse_MonitorWall_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MonitorWall::_decoderOutTVNumResponse_default_instance_;
    new (ptr) ::MonitorWall::decoderOutTVNumResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MonitorWall::decoderOutTVNumResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_decoderOutTVNumResponse_MonitorWall_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_decoderOutTVNumResponse_MonitorWall_2eproto}, {
      &scc_info_loginRequest_MonitorWall_2eproto.base,}};

static void InitDefaultsscc_info_empty_MonitorWall_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MonitorWall::_empty_default_instance_;
    new (ptr) ::MonitorWall::empty();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MonitorWall::empty::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_empty_MonitorWall_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_empty_MonitorWall_2eproto}, {}};

static void InitDefaultsscc_info_loginRequest_MonitorWall_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MonitorWall::_loginRequest_default_instance_;
    new (ptr) ::MonitorWall::loginRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MonitorWall::loginRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_loginRequest_MonitorWall_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_loginRequest_MonitorWall_2eproto}, {}};

static void InitDefaultsscc_info_wallConfigRequest_MonitorWall_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MonitorWall::_wallConfigRequest_default_instance_;
    new (ptr) ::MonitorWall::wallConfigRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MonitorWall::wallConfigRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_wallConfigRequest_MonitorWall_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_wallConfigRequest_MonitorWall_2eproto}, {
      &scc_info_blockMes_MonitorWall_2eproto.base,
      &scc_info_loginRequest_MonitorWall_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_MonitorWall_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_MonitorWall_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_MonitorWall_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_MonitorWall_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::loginRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::loginRequest, decoder_ip_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::loginRequest, decoder_port_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::loginRequest, decoder_username_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::loginRequest, decoder_pwd_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::decoderOutTVNumResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::decoderOutTVNumResponse, tv_num_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::decoderOutTVNumResponse, login_res_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::blockMes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::blockMes, bind_line_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::blockMes, bind_col_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::blockMes, bind_ch_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::wallConfigRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MonitorWall::wallConfigRequest, line_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::wallConfigRequest, colunm_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::wallConfigRequest, block_),
  PROTOBUF_FIELD_OFFSET(::MonitorWall::wallConfigRequest, login_res_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MonitorWall::empty)},
  { 5, -1, sizeof(::MonitorWall::loginRequest)},
  { 14, -1, sizeof(::MonitorWall::decoderOutTVNumResponse)},
  { 21, -1, sizeof(::MonitorWall::blockMes)},
  { 29, -1, sizeof(::MonitorWall::wallConfigRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MonitorWall::_empty_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MonitorWall::_loginRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MonitorWall::_decoderOutTVNumResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MonitorWall::_blockMes_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MonitorWall::_wallConfigRequest_default_instance_),
};

const char descriptor_table_protodef_MonitorWall_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021MonitorWall.proto\022\013MonitorWall\"\007\n\005empt"
  "y\"g\n\014loginRequest\022\022\n\ndecoder_ip\030\001 \001(\t\022\024\n"
  "\014decoder_port\030\002 \001(\r\022\030\n\020decoder_username\030"
  "\003 \001(\t\022\023\n\013decoder_pwd\030\004 \001(\t\"W\n\027decoderOut"
  "TVNumResponse\022\016\n\006tv_num\030\001 \001(\005\022,\n\tlogin_r"
  "es\030\002 \001(\0132\031.MonitorWall.loginRequest\"@\n\010b"
  "lockMes\022\021\n\tbind_line\030\001 \001(\005\022\020\n\010bind_col\030\002"
  " \001(\005\022\017\n\007bind_ch\030\003 \001(\005\"\205\001\n\021wallConfigRequ"
  "est\022\014\n\004line\030\001 \001(\005\022\016\n\006colunm\030\002 \001(\005\022$\n\005blo"
  "ck\030\003 \003(\0132\025.MonitorWall.blockMes\022,\n\tlogin"
  "_res\030\004 \001(\0132\031.MonitorWall.loginRequest2\336\001"
  "\n\017SWKJMonitorWall\0228\n\005login\022\031.MonitorWall"
  ".loginRequest\032\022.MonitorWall.empty\"\000\022M\n\010g"
  "etTVNum\022\031.MonitorWall.loginRequest\032$.Mon"
  "itorWall.decoderOutTVNumResponse\"\000\022B\n\ncr"
  "eateWall\022\036.MonitorWall.wallConfigRequest"
  "\032\022.MonitorWall.empty\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_MonitorWall_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_MonitorWall_2eproto_sccs[5] = {
  &scc_info_blockMes_MonitorWall_2eproto.base,
  &scc_info_decoderOutTVNumResponse_MonitorWall_2eproto.base,
  &scc_info_empty_MonitorWall_2eproto.base,
  &scc_info_loginRequest_MonitorWall_2eproto.base,
  &scc_info_wallConfigRequest_MonitorWall_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_MonitorWall_2eproto_once;
static bool descriptor_table_MonitorWall_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MonitorWall_2eproto = {
  &descriptor_table_MonitorWall_2eproto_initialized, descriptor_table_protodef_MonitorWall_2eproto, "MonitorWall.proto", 670,
  &descriptor_table_MonitorWall_2eproto_once, descriptor_table_MonitorWall_2eproto_sccs, descriptor_table_MonitorWall_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_MonitorWall_2eproto::offsets,
  file_level_metadata_MonitorWall_2eproto, 5, file_level_enum_descriptors_MonitorWall_2eproto, file_level_service_descriptors_MonitorWall_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MonitorWall_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_MonitorWall_2eproto), true);
namespace MonitorWall {

// ===================================================================

void empty::InitAsDefaultInstance() {
}
class empty::_Internal {
 public:
};

empty::empty()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MonitorWall.empty)
}
empty::empty(const empty& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:MonitorWall.empty)
}

void empty::SharedCtor() {
}

empty::~empty() {
  // @@protoc_insertion_point(destructor:MonitorWall.empty)
  SharedDtor();
}

void empty::SharedDtor() {
}

void empty::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const empty& empty::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_empty_MonitorWall_2eproto.base);
  return *internal_default_instance();
}


void empty::Clear() {
// @@protoc_insertion_point(message_clear_start:MonitorWall.empty)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

const char* empty::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* empty::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MonitorWall.empty)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MonitorWall.empty)
  return target;
}

size_t empty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MonitorWall.empty)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void empty::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MonitorWall.empty)
  GOOGLE_DCHECK_NE(&from, this);
  const empty* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<empty>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MonitorWall.empty)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MonitorWall.empty)
    MergeFrom(*source);
  }
}

void empty::MergeFrom(const empty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MonitorWall.empty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void empty::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MonitorWall.empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void empty::CopyFrom(const empty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MonitorWall.empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool empty::IsInitialized() const {
  return true;
}

void empty::InternalSwap(empty* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata empty::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void loginRequest::InitAsDefaultInstance() {
}
class loginRequest::_Internal {
 public:
};

loginRequest::loginRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MonitorWall.loginRequest)
}
loginRequest::loginRequest(const loginRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  decoder_ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_decoder_ip().empty()) {
    decoder_ip_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.decoder_ip_);
  }
  decoder_username_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_decoder_username().empty()) {
    decoder_username_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.decoder_username_);
  }
  decoder_pwd_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_decoder_pwd().empty()) {
    decoder_pwd_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.decoder_pwd_);
  }
  decoder_port_ = from.decoder_port_;
  // @@protoc_insertion_point(copy_constructor:MonitorWall.loginRequest)
}

void loginRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_loginRequest_MonitorWall_2eproto.base);
  decoder_ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_username_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_pwd_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_port_ = 0u;
}

loginRequest::~loginRequest() {
  // @@protoc_insertion_point(destructor:MonitorWall.loginRequest)
  SharedDtor();
}

void loginRequest::SharedDtor() {
  decoder_ip_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_username_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_pwd_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void loginRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const loginRequest& loginRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_loginRequest_MonitorWall_2eproto.base);
  return *internal_default_instance();
}


void loginRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MonitorWall.loginRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  decoder_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_username_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_pwd_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  decoder_port_ = 0u;
  _internal_metadata_.Clear();
}

const char* loginRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string decoder_ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_decoder_ip();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MonitorWall.loginRequest.decoder_ip"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 decoder_port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          decoder_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string decoder_username = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_decoder_username();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MonitorWall.loginRequest.decoder_username"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string decoder_pwd = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_decoder_pwd();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MonitorWall.loginRequest.decoder_pwd"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* loginRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MonitorWall.loginRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string decoder_ip = 1;
  if (this->decoder_ip().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_decoder_ip().data(), static_cast<int>(this->_internal_decoder_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MonitorWall.loginRequest.decoder_ip");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_decoder_ip(), target);
  }

  // uint32 decoder_port = 2;
  if (this->decoder_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_decoder_port(), target);
  }

  // string decoder_username = 3;
  if (this->decoder_username().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_decoder_username().data(), static_cast<int>(this->_internal_decoder_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MonitorWall.loginRequest.decoder_username");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_decoder_username(), target);
  }

  // string decoder_pwd = 4;
  if (this->decoder_pwd().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_decoder_pwd().data(), static_cast<int>(this->_internal_decoder_pwd().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MonitorWall.loginRequest.decoder_pwd");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_decoder_pwd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MonitorWall.loginRequest)
  return target;
}

size_t loginRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MonitorWall.loginRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string decoder_ip = 1;
  if (this->decoder_ip().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_decoder_ip());
  }

  // string decoder_username = 3;
  if (this->decoder_username().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_decoder_username());
  }

  // string decoder_pwd = 4;
  if (this->decoder_pwd().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_decoder_pwd());
  }

  // uint32 decoder_port = 2;
  if (this->decoder_port() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_decoder_port());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void loginRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MonitorWall.loginRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const loginRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<loginRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MonitorWall.loginRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MonitorWall.loginRequest)
    MergeFrom(*source);
  }
}

void loginRequest::MergeFrom(const loginRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MonitorWall.loginRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.decoder_ip().size() > 0) {

    decoder_ip_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.decoder_ip_);
  }
  if (from.decoder_username().size() > 0) {

    decoder_username_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.decoder_username_);
  }
  if (from.decoder_pwd().size() > 0) {

    decoder_pwd_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.decoder_pwd_);
  }
  if (from.decoder_port() != 0) {
    _internal_set_decoder_port(from._internal_decoder_port());
  }
}

void loginRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MonitorWall.loginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void loginRequest::CopyFrom(const loginRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MonitorWall.loginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool loginRequest::IsInitialized() const {
  return true;
}

void loginRequest::InternalSwap(loginRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  decoder_ip_.Swap(&other->decoder_ip_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  decoder_username_.Swap(&other->decoder_username_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  decoder_pwd_.Swap(&other->decoder_pwd_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(decoder_port_, other->decoder_port_);
}

::PROTOBUF_NAMESPACE_ID::Metadata loginRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void decoderOutTVNumResponse::InitAsDefaultInstance() {
  ::MonitorWall::_decoderOutTVNumResponse_default_instance_._instance.get_mutable()->login_res_ = const_cast< ::MonitorWall::loginRequest*>(
      ::MonitorWall::loginRequest::internal_default_instance());
}
class decoderOutTVNumResponse::_Internal {
 public:
  static const ::MonitorWall::loginRequest& login_res(const decoderOutTVNumResponse* msg);
};

const ::MonitorWall::loginRequest&
decoderOutTVNumResponse::_Internal::login_res(const decoderOutTVNumResponse* msg) {
  return *msg->login_res_;
}
decoderOutTVNumResponse::decoderOutTVNumResponse()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MonitorWall.decoderOutTVNumResponse)
}
decoderOutTVNumResponse::decoderOutTVNumResponse(const decoderOutTVNumResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_login_res()) {
    login_res_ = new ::MonitorWall::loginRequest(*from.login_res_);
  } else {
    login_res_ = nullptr;
  }
  tv_num_ = from.tv_num_;
  // @@protoc_insertion_point(copy_constructor:MonitorWall.decoderOutTVNumResponse)
}

void decoderOutTVNumResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_decoderOutTVNumResponse_MonitorWall_2eproto.base);
  ::memset(&login_res_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tv_num_) -
      reinterpret_cast<char*>(&login_res_)) + sizeof(tv_num_));
}

decoderOutTVNumResponse::~decoderOutTVNumResponse() {
  // @@protoc_insertion_point(destructor:MonitorWall.decoderOutTVNumResponse)
  SharedDtor();
}

void decoderOutTVNumResponse::SharedDtor() {
  if (this != internal_default_instance()) delete login_res_;
}

void decoderOutTVNumResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const decoderOutTVNumResponse& decoderOutTVNumResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_decoderOutTVNumResponse_MonitorWall_2eproto.base);
  return *internal_default_instance();
}


void decoderOutTVNumResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MonitorWall.decoderOutTVNumResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && login_res_ != nullptr) {
    delete login_res_;
  }
  login_res_ = nullptr;
  tv_num_ = 0;
  _internal_metadata_.Clear();
}

const char* decoderOutTVNumResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 tv_num = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          tv_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .MonitorWall.loginRequest login_res = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_login_res(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* decoderOutTVNumResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MonitorWall.decoderOutTVNumResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tv_num = 1;
  if (this->tv_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_tv_num(), target);
  }

  // .MonitorWall.loginRequest login_res = 2;
  if (this->has_login_res()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::login_res(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MonitorWall.decoderOutTVNumResponse)
  return target;
}

size_t decoderOutTVNumResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MonitorWall.decoderOutTVNumResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .MonitorWall.loginRequest login_res = 2;
  if (this->has_login_res()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *login_res_);
  }

  // int32 tv_num = 1;
  if (this->tv_num() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_tv_num());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void decoderOutTVNumResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MonitorWall.decoderOutTVNumResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const decoderOutTVNumResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<decoderOutTVNumResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MonitorWall.decoderOutTVNumResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MonitorWall.decoderOutTVNumResponse)
    MergeFrom(*source);
  }
}

void decoderOutTVNumResponse::MergeFrom(const decoderOutTVNumResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MonitorWall.decoderOutTVNumResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_login_res()) {
    _internal_mutable_login_res()->::MonitorWall::loginRequest::MergeFrom(from._internal_login_res());
  }
  if (from.tv_num() != 0) {
    _internal_set_tv_num(from._internal_tv_num());
  }
}

void decoderOutTVNumResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MonitorWall.decoderOutTVNumResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void decoderOutTVNumResponse::CopyFrom(const decoderOutTVNumResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MonitorWall.decoderOutTVNumResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool decoderOutTVNumResponse::IsInitialized() const {
  return true;
}

void decoderOutTVNumResponse::InternalSwap(decoderOutTVNumResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(login_res_, other->login_res_);
  swap(tv_num_, other->tv_num_);
}

::PROTOBUF_NAMESPACE_ID::Metadata decoderOutTVNumResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void blockMes::InitAsDefaultInstance() {
}
class blockMes::_Internal {
 public:
};

blockMes::blockMes()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MonitorWall.blockMes)
}
blockMes::blockMes(const blockMes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&bind_line_, &from.bind_line_,
    static_cast<size_t>(reinterpret_cast<char*>(&bind_ch_) -
    reinterpret_cast<char*>(&bind_line_)) + sizeof(bind_ch_));
  // @@protoc_insertion_point(copy_constructor:MonitorWall.blockMes)
}

void blockMes::SharedCtor() {
  ::memset(&bind_line_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bind_ch_) -
      reinterpret_cast<char*>(&bind_line_)) + sizeof(bind_ch_));
}

blockMes::~blockMes() {
  // @@protoc_insertion_point(destructor:MonitorWall.blockMes)
  SharedDtor();
}

void blockMes::SharedDtor() {
}

void blockMes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const blockMes& blockMes::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_blockMes_MonitorWall_2eproto.base);
  return *internal_default_instance();
}


void blockMes::Clear() {
// @@protoc_insertion_point(message_clear_start:MonitorWall.blockMes)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&bind_line_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bind_ch_) -
      reinterpret_cast<char*>(&bind_line_)) + sizeof(bind_ch_));
  _internal_metadata_.Clear();
}

const char* blockMes::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 bind_line = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          bind_line_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 bind_col = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          bind_col_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 bind_ch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          bind_ch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* blockMes::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MonitorWall.blockMes)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 bind_line = 1;
  if (this->bind_line() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_bind_line(), target);
  }

  // int32 bind_col = 2;
  if (this->bind_col() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_bind_col(), target);
  }

  // int32 bind_ch = 3;
  if (this->bind_ch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_bind_ch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MonitorWall.blockMes)
  return target;
}

size_t blockMes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MonitorWall.blockMes)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 bind_line = 1;
  if (this->bind_line() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_bind_line());
  }

  // int32 bind_col = 2;
  if (this->bind_col() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_bind_col());
  }

  // int32 bind_ch = 3;
  if (this->bind_ch() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_bind_ch());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void blockMes::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MonitorWall.blockMes)
  GOOGLE_DCHECK_NE(&from, this);
  const blockMes* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<blockMes>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MonitorWall.blockMes)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MonitorWall.blockMes)
    MergeFrom(*source);
  }
}

void blockMes::MergeFrom(const blockMes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MonitorWall.blockMes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bind_line() != 0) {
    _internal_set_bind_line(from._internal_bind_line());
  }
  if (from.bind_col() != 0) {
    _internal_set_bind_col(from._internal_bind_col());
  }
  if (from.bind_ch() != 0) {
    _internal_set_bind_ch(from._internal_bind_ch());
  }
}

void blockMes::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MonitorWall.blockMes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void blockMes::CopyFrom(const blockMes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MonitorWall.blockMes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool blockMes::IsInitialized() const {
  return true;
}

void blockMes::InternalSwap(blockMes* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(bind_line_, other->bind_line_);
  swap(bind_col_, other->bind_col_);
  swap(bind_ch_, other->bind_ch_);
}

::PROTOBUF_NAMESPACE_ID::Metadata blockMes::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void wallConfigRequest::InitAsDefaultInstance() {
  ::MonitorWall::_wallConfigRequest_default_instance_._instance.get_mutable()->login_res_ = const_cast< ::MonitorWall::loginRequest*>(
      ::MonitorWall::loginRequest::internal_default_instance());
}
class wallConfigRequest::_Internal {
 public:
  static const ::MonitorWall::loginRequest& login_res(const wallConfigRequest* msg);
};

const ::MonitorWall::loginRequest&
wallConfigRequest::_Internal::login_res(const wallConfigRequest* msg) {
  return *msg->login_res_;
}
wallConfigRequest::wallConfigRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MonitorWall.wallConfigRequest)
}
wallConfigRequest::wallConfigRequest(const wallConfigRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      block_(from.block_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_login_res()) {
    login_res_ = new ::MonitorWall::loginRequest(*from.login_res_);
  } else {
    login_res_ = nullptr;
  }
  ::memcpy(&line_, &from.line_,
    static_cast<size_t>(reinterpret_cast<char*>(&colunm_) -
    reinterpret_cast<char*>(&line_)) + sizeof(colunm_));
  // @@protoc_insertion_point(copy_constructor:MonitorWall.wallConfigRequest)
}

void wallConfigRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_wallConfigRequest_MonitorWall_2eproto.base);
  ::memset(&login_res_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&colunm_) -
      reinterpret_cast<char*>(&login_res_)) + sizeof(colunm_));
}

wallConfigRequest::~wallConfigRequest() {
  // @@protoc_insertion_point(destructor:MonitorWall.wallConfigRequest)
  SharedDtor();
}

void wallConfigRequest::SharedDtor() {
  if (this != internal_default_instance()) delete login_res_;
}

void wallConfigRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const wallConfigRequest& wallConfigRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_wallConfigRequest_MonitorWall_2eproto.base);
  return *internal_default_instance();
}


void wallConfigRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MonitorWall.wallConfigRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  block_.Clear();
  if (GetArenaNoVirtual() == nullptr && login_res_ != nullptr) {
    delete login_res_;
  }
  login_res_ = nullptr;
  ::memset(&line_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&colunm_) -
      reinterpret_cast<char*>(&line_)) + sizeof(colunm_));
  _internal_metadata_.Clear();
}

const char* wallConfigRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 line = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          line_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 colunm = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          colunm_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .MonitorWall.blockMes block = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_block(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // .MonitorWall.loginRequest login_res = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_login_res(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* wallConfigRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MonitorWall.wallConfigRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 line = 1;
  if (this->line() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_line(), target);
  }

  // int32 colunm = 2;
  if (this->colunm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_colunm(), target);
  }

  // repeated .MonitorWall.blockMes block = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_block_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_block(i), target, stream);
  }

  // .MonitorWall.loginRequest login_res = 4;
  if (this->has_login_res()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::login_res(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MonitorWall.wallConfigRequest)
  return target;
}

size_t wallConfigRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MonitorWall.wallConfigRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .MonitorWall.blockMes block = 3;
  total_size += 1UL * this->_internal_block_size();
  for (const auto& msg : this->block_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .MonitorWall.loginRequest login_res = 4;
  if (this->has_login_res()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *login_res_);
  }

  // int32 line = 1;
  if (this->line() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_line());
  }

  // int32 colunm = 2;
  if (this->colunm() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_colunm());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void wallConfigRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MonitorWall.wallConfigRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const wallConfigRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<wallConfigRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MonitorWall.wallConfigRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MonitorWall.wallConfigRequest)
    MergeFrom(*source);
  }
}

void wallConfigRequest::MergeFrom(const wallConfigRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MonitorWall.wallConfigRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  block_.MergeFrom(from.block_);
  if (from.has_login_res()) {
    _internal_mutable_login_res()->::MonitorWall::loginRequest::MergeFrom(from._internal_login_res());
  }
  if (from.line() != 0) {
    _internal_set_line(from._internal_line());
  }
  if (from.colunm() != 0) {
    _internal_set_colunm(from._internal_colunm());
  }
}

void wallConfigRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MonitorWall.wallConfigRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void wallConfigRequest::CopyFrom(const wallConfigRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MonitorWall.wallConfigRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool wallConfigRequest::IsInitialized() const {
  return true;
}

void wallConfigRequest::InternalSwap(wallConfigRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  block_.InternalSwap(&other->block_);
  swap(login_res_, other->login_res_);
  swap(line_, other->line_);
  swap(colunm_, other->colunm_);
}

::PROTOBUF_NAMESPACE_ID::Metadata wallConfigRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MonitorWall
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MonitorWall::empty* Arena::CreateMaybeMessage< ::MonitorWall::empty >(Arena* arena) {
  return Arena::CreateInternal< ::MonitorWall::empty >(arena);
}
template<> PROTOBUF_NOINLINE ::MonitorWall::loginRequest* Arena::CreateMaybeMessage< ::MonitorWall::loginRequest >(Arena* arena) {
  return Arena::CreateInternal< ::MonitorWall::loginRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::MonitorWall::decoderOutTVNumResponse* Arena::CreateMaybeMessage< ::MonitorWall::decoderOutTVNumResponse >(Arena* arena) {
  return Arena::CreateInternal< ::MonitorWall::decoderOutTVNumResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::MonitorWall::blockMes* Arena::CreateMaybeMessage< ::MonitorWall::blockMes >(Arena* arena) {
  return Arena::CreateInternal< ::MonitorWall::blockMes >(arena);
}
template<> PROTOBUF_NOINLINE ::MonitorWall::wallConfigRequest* Arena::CreateMaybeMessage< ::MonitorWall::wallConfigRequest >(Arena* arena) {
  return Arena::CreateInternal< ::MonitorWall::wallConfigRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
